name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true

      - name: Install dependencies
        run: pnpm install

      - name: Build the site
        run: pnpm astro build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist # Asegúrate de que este sea el directorio de salida de tu build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Upload to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: ./dist
